import IMAGES from "../constants/images";
import DoctorAvatars from "../components/DoctorAvatars";
import { useEffect, useRef, useState } from "react";
const P={drGill:"/assets/dr-gill-outdoor.jpg",drGillIn:"/assets/dr J gill-inside.jpg",consult1:"/assets/indoor1.jpg"              /* ✅ clean clinic interior */,consult2:"/assets/both-doctors-clinic.jpg"  /* ✅ both doctors in clinic */,inside:"/assets/inside clinic1.jpg"};
function useReveal(t=0.12){const ref=useRef(null);const[v,sv]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting){sv(true);o.unobserve(el);}},{threshold:t,rootMargin:"0px 0px -60px 0px"});o.observe(el);return()=>o.disconnect();},[t]);return[ref,v];}
function Cursor(){const d=useRef(null),r=useRef(null),p=useRef({x:0,y:0}),f=useRef(null);useEffect(()=>{const mv=e=>{p.current={x:e.clientX,y:e.clientY};};const tk=()=>{if(d.current)d.current.style.transform=`translate(${p.current.x-4}px,${p.current.y-4}px)`;if(r.current)r.current.style.transform=`translate(${p.current.x-16}px,${p.current.y-16}px)`;f.current=requestAnimationFrame(tk);};window.addEventListener("mousemove",mv);f.current=requestAnimationFrame(tk);return()=>{window.removeEventListener("mousemove",mv);cancelAnimationFrame(f.current);};},[]);return(<><div ref={d} className="fixed top-0 left-0 w-2 h-2 rounded-full bg-[#B8925A] z-[9999] pointer-events-none" style={{transition:"none"}}/><div ref={r} className="fixed top-0 left-0 w-8 h-8 rounded-full border border-[#B8925A]/50 z-[9998] pointer-events-none" style={{transition:"transform 0.12s ease-out"}}/></>);}
export default function Telehealth(){
  return(<main style={{fontFamily:"'Jost',sans-serif",background:"#FDFAF6",cursor:"none"}}><style>{CSS}</style><Cursor/><Hero/><Mq/><WhatWeTreat/><HowWorks/><CASection/><WhyCover/><FAQSec/><CTA/></main>);
}
function Hero(){
  const[on,sOn]=useState(false);useEffect(()=>{setTimeout(()=>sOn(true),80);},[]);
  return(
    <section className="relative min-h-[88vh] flex items-end overflow-hidden" style={{background:"linear-gradient(140deg,#263320 0%,#1E2B1C 55%,#192417 100%)"}}>
      <div className="absolute inset-0 opacity-[0.06] pointer-events-none" style={{backgroundImage:"radial-gradient(circle,#fff 1px,transparent 1px)",backgroundSize:"32px 32px"}}/>
      <div className="absolute right-0 top-0 bottom-0 w-full lg:w-[52%] overflow-hidden"><img src={P.consult1} alt="Telehealth" className="w-full h-full object-cover opacity-35" style={{filter:"saturate(0.6)"}}/><div className="absolute inset-0" style={{background:"linear-gradient(to right,#1E2B1C 0%,#1E2B1C 12%,transparent 58%)"}}/><div className="absolute inset-0" style={{background:"linear-gradient(to top,#1E2B1C 0%,transparent 55%)"}}/></div>
      {[{t:"10%",l:"52%",s:400,o:0.10,d:"0s"},{t:"60%",l:"5%",s:260,o:0.07,d:"5s"}].map((o,i)=>(<div key={i} className="absolute rounded-full pointer-events-none" style={{width:o.s,height:o.s,top:o.t,left:o.l,background:`radial-gradient(circle,rgba(168,197,154,${o.o}) 0%,transparent 70%)`,animation:`floatOrb ${11+i*4}s ease-in-out infinite ${o.d}`}}/>))}
      <div className="hidden xl:flex absolute right-8 top-1/2 -translate-y-1/2 flex-col items-center gap-3" style={{writingMode:"vertical-rl",animation:"fadeUp 1s ease 0.8s both"}}><span className="w-px h-16 bg-[#A8C59A]/40"/><span className="text-[9px] tracking-[0.3em] uppercase text-[#A8C59A]/50">Available · All of California</span><span className="w-px h-16 bg-[#A8C59A]/40"/></div>
      <div className="relative mx-auto max-w-7xl w-full px-5 md:px-10 xl:px-16 pb-20 pt-36 grid grid-cols-1 lg:grid-cols-2 gap-10 items-end">
        <div>
          <div className={`inline-flex items-center gap-2.5 border border-[#A8C59A]/40 bg-[#A8C59A]/8 px-4 py-2 mb-7 transition-all duration-700 ${on?"opacity-100 translate-y-0":"opacity-0 translate-y-6"}`} style={{transitionDelay:"100ms"}}><span className="w-1.5 h-1.5 rounded-full bg-[#A8C59A] animate-pulse"/><span className="text-[10px] tracking-[0.24em] uppercase text-[#A8C59A] font-semibold">Available Statewide · All of California</span></div>
          <h1 className={`text-[48px] md:text-[62px] xl:text-[74px] text-[#F0EDE8] leading-[0.98] mb-5 transition-all duration-900 ${on?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`} style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:300,transitionDelay:"200ms"}}>Your Psychiatrist.<br/><em className="italic text-[#A8C59A]">Wherever</em><br/>You Are.</h1>
          <p className={`text-[#A8B89E] text-lg leading-relaxed max-w-lg font-light mb-10 transition-all duration-700 ${on?"opacity-100 translate-y-0":"opacity-0 translate-y-6"}`} style={{transitionDelay:"440ms"}}>Dr. Gill offers HIPAA-compliant telehealth psychiatric appointments to patients anywhere in California. Same expertise. Same personal attention. From the comfort of your home, office, or anywhere with a connection.</p>
          <div className={`flex flex-wrap gap-4 mb-8 transition-all duration-700 ${on?"opacity-100 translate-y-0":"opacity-0 translate-y-6"}`} style={{transitionDelay:"540ms"}}>
            <a href="/contact" className="group flex items-center gap-3 bg-[#6B7C5E] text-[#F0EDE8] px-8 py-4 text-[11px] font-bold tracking-[0.2em] uppercase hover:bg-[#7D9170] transition-colors duration-300"><Ph/> Book Telehealth Visit <span className="group-hover:translate-x-1.5 transition-transform duration-300">→</span></a>
            <a href="#how-it-works" className="flex items-center gap-3 border border-[#A8C59A]/40 text-[#A8C59A] px-8 py-4 text-[11px] font-bold tracking-[0.2em] uppercase hover:border-[#A8C59A] hover:bg-[#A8C59A]/10 transition-all duration-300">How It Works ↓</a>
          </div>
          <div className={`flex flex-wrap gap-3 transition-all duration-700 ${on?"opacity-100":"opacity-0"}`} style={{transitionDelay:"640ms"}}>
            {["All of California","HIPAA-Compliant","Insurance Covered","Next-Day Available"].map(t=>(<span key={t} className="text-[9px] tracking-[0.18em] uppercase border border-[#A8C59A]/25 text-[#A8C59A]/60 px-3 py-1.5">{t}</span>))}
          </div>
        </div>
        <div className={`hidden lg:flex flex-col gap-4 items-end transition-all duration-1000 ${on?"opacity-100 translate-y-0":"opacity-0 translate-y-10"}`} style={{transitionDelay:"380ms"}}>
          {[{val:"All",lab:"of California",sub:"No geographic restrictions"},{val:"HIPAA",lab:"Compliant Platform",sub:"Bank-level secure video"},{val:"Same",lab:"Quality of Care",sub:"Identical to in-person visits"}].map((c,i)=>(<div key={c.lab} className="bg-[#1E2B1C]/60 border border-[#A8C59A]/20 px-6 py-5 flex items-center gap-5 w-full max-w-xs" style={{animation:`fadeUp 0.8s ease ${0.5+i*0.12}s both`}}><p className="text-3xl text-[#A8C59A] flex-shrink-0" style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:300}}>{c.val}</p><div><p className="text-[#F0EDE8] text-sm font-medium">{c.lab}</p><p className="text-[#A8B89E] text-xs font-light mt-0.5">{c.sub}</p></div></div>))}
        </div>
      </div>
      <div className="absolute bottom-0 left-0 right-0 h-28 pointer-events-none" style={{background:"linear-gradient(to top,#FDFAF6,transparent)"}}/>
    </section>
  );
}
function Mq(){const items=["Telehealth Psychiatry","Virtual Appointments","All of California","HIPAA-Compliant","Anxiety","Depression","ADHD","PTSD","Bipolar Disorder","Medication Management","Insurance Covered","Next-Day Scheduling"];const rep=[...items,...items];return(<div className="bg-[#1E2B1C] py-3.5 overflow-hidden"><div className="flex whitespace-nowrap" style={{animation:"marquee 38s linear infinite",width:"max-content"}}>{rep.map((t,i)=><span key={i} className="inline-flex items-center gap-3 text-[#A8B89E]/60 text-[10px] tracking-[0.22em] uppercase font-medium px-3">{t}<svg width="6" height="6" viewBox="0 0 10 10" fill="#6B7C5E"><polygon points="5,0 10,5 5,10 0,5"/></svg></span>)}</div></div>);}
function WhatWeTreat(){
  const[ref,v]=useReveal();
  const conds=[["Anxiety Disorders","GAD · Panic · Social Anxiety"],["Major Depression","MDD · Persistent Depressive"],["ADHD","Adult Diagnosis & Management"],["PTSD & Trauma","Complex & Single-Event"],["Bipolar Disorder","Type I & Type II"],["OCD","Obsessive-Compulsive Disorder"],["Insomnia","Chronic Sleep Disorders"],["Medication Mgmt","Prescription & Refills"]];
  return(<section className="py-24 px-5 md:px-10 bg-[#FDFAF6]"><div className="mx-auto max-w-7xl">
    <div ref={ref} className="text-center mb-14"><div className={`flex items-center justify-center gap-3 mb-5 transition-all duration-700 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`}><span className="w-12 h-px bg-[#6B7C5E]/50"/><svg width="7" height="7" viewBox="0 0 10 10" fill="#6B7C5E"><polygon points="5,0 10,5 5,10 0,5"/></svg><span className="w-12 h-px bg-[#6B7C5E]/50"/></div><h2 className={`text-5xl md:text-6xl text-[#2C1A0E] mb-4 transition-all duration-700 delay-100 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`} style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:300}}>What We Treat <em className="italic text-[#6B7C5E]">via Telehealth</em></h2><p className={`text-[#7A6556] text-lg font-light max-w-xl mx-auto transition-all duration-700 delay-200 ${v?"opacity-100":"opacity-0"}`}>Everything Dr. Gill treats in person is also available via telehealth — for any patient in California.</p></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
      {conds.map(([t,s],i)=>(<div key={t} className={`group border border-[#E8D5BE] bg-[#F5EEE4] p-6 text-center transition-all duration-700 hover:-translate-y-1.5 hover:shadow-[0_12px_40px_rgba(107,124,94,0.12)] hover:border-[#6B7C5E]/50 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`} style={{transitionDelay:`${i*80}ms`,transitionDuration:"600ms"}}><div className="absolute top-0 left-0 right-0 h-[2px] bg-[#6B7C5E] scale-x-0 group-hover:scale-x-100 transition-transform duration-500 origin-left relative"/><h3 className="text-lg text-[#2C1A0E] mb-1" style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:500}}>{t}</h3><p className="text-[10px] tracking-[0.16em] uppercase text-[#6B7C5E] font-medium">{s}</p></div>))}
    </div>
    <div className={`mt-8 text-center transition-all duration-700 delay-700 ${v?"opacity-100":"opacity-0"}`}><p className="text-[#7A6556] text-sm font-light">Don't see your condition? <a href="tel:5105984921" className="text-[#6B7C5E] underline underline-offset-2 hover:text-[#B8925A] transition-colors">Call us</a> — Dr. Gill treats many more via telehealth.</p></div>
  </div></section>);
}
function HowWorks(){
  const[ref,v]=useReveal();
  const steps=[{n:"01",t:"Call or Contact Us",d:"Reach out by phone or the contact form. We'll verify your insurance and schedule your telehealth appointment."},{n:"02",t:"Receive Secure Link",d:"A HIPAA-compliant video link is sent to your email before your session. No app download required — works in your browser."},{n:"03",t:"Meet Dr. Gill",d:"Join from anywhere in California — home, office, or anywhere private. Your appointment runs exactly like an in-person visit."},{n:"04",t:"Ongoing Care",d:"Follow-up appointments, prescription management, and medication refills — all handled via telehealth without interruption."}];
  return(<section id="how-it-works" className="py-24 px-5 md:px-10" style={{background:"linear-gradient(140deg,#263320 0%,#1E2B1C 100%)"}}><div className="absolute inset-0 opacity-[0.05] pointer-events-none" style={{backgroundImage:"radial-gradient(circle,#fff 1px,transparent 1px)",backgroundSize:"28px 28px"}}/>
  <div className="relative mx-auto max-w-7xl">
    <div ref={ref} className="text-center mb-16"><div className={`flex items-center justify-center gap-3 mb-5 transition-all duration-700 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`}><span className="w-12 h-px bg-[#A8C59A]/40"/><svg width="7" height="7" viewBox="0 0 10 10" fill="#A8C59A"><polygon points="5,0 10,5 5,10 0,5"/></svg><span className="w-12 h-px bg-[#A8C59A]/40"/></div><h2 className={`text-5xl md:text-6xl text-[#F0EDE8] transition-all duration-700 delay-100 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`} style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:300}}>How Telehealth <em className="italic text-[#A8C59A]">Works</em></h2></div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 relative"><div className="hidden lg:block absolute top-12 left-[12.5%] right-[12.5%] h-px bg-gradient-to-r from-[#A8C59A]/20 via-[#A8C59A]/50 to-[#A8C59A]/20"/>
    {steps.map((s,i)=>(<div key={s.n} className={`group text-center transition-all duration-700 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-10"}`} style={{transitionDelay:`${i*140}ms`,transitionDuration:"700ms"}}><div className="relative inline-flex items-center justify-center w-24 h-24 mb-6 mx-auto"><div className="absolute inset-0 rounded-full border-2 border-[#A8C59A]/30 group-hover:border-[#A8C59A] transition-colors duration-500"/><div className="absolute inset-[6px] rounded-full bg-[#A8C59A]/8 group-hover:bg-[#A8C59A]/15 transition-all duration-500"/><span className="text-2xl text-[#A8C59A]" style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:300}}>{s.n}</span></div><h3 className="text-xl text-[#F0EDE8] mb-3 group-hover:text-[#A8C59A] transition-colors duration-300" style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:500}}>{s.t}</h3><p className="text-[#A8B89E] text-sm leading-relaxed font-light max-w-[210px] mx-auto">{s.d}</p></div>))}
    </div>
    <div className={`mt-14 text-center transition-all duration-700 delay-700 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-6"}`}><a href="/contact" className="group inline-flex items-center gap-3 bg-[#6B7C5E] text-[#F0EDE8] px-10 py-4 text-[11px] font-bold tracking-[0.2em] uppercase hover:bg-[#7D9170] transition-colors duration-300"><Ph/> Book Your Telehealth Visit <span className="group-hover:translate-x-1.5 transition-transform duration-300">→</span></a></div>
  </div></section>);
}
function CASection(){
  const[ref,v]=useReveal();
  const cities=["Los Angeles","San Diego","San Francisco","Sacramento","San Jose","Oakland","Fresno","Bakersfield","Long Beach","Anaheim","Santa Ana","Riverside","Stockton","Chula Vista","Irvine","Fremont","San Bernardino","Modesto","Fontana","Moreno Valley","Glendale","Huntington Beach","Santa Clarita","Garden Grove","Santa Rosa","Oceanside","Rancho Cucamonga","Ontario","Lancaster","Elk Grove","Corona","Palmdale","Salinas","Pomona","Hayward","Sunnyvale","Escondido","Torrance","Pasadena","Orange"];
  return(<section className="py-24 px-5 md:px-10 bg-[#F5EEE4]"><div className="mx-auto max-w-7xl">
    <div ref={ref} className="text-center mb-14"><div className={`flex items-center justify-center gap-3 mb-5 transition-all duration-700 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`}><span className="w-12 h-px bg-[#6B7C5E]/50"/><svg width="7" height="7" viewBox="0 0 10 10" fill="#6B7C5E"><polygon points="5,0 10,5 5,10 0,5"/></svg><span className="w-12 h-px bg-[#6B7C5E]/50"/></div><h2 className={`text-5xl md:text-6xl text-[#2C1A0E] mb-4 transition-all duration-700 delay-100 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`} style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:300}}>Serving All of <em className="italic text-[#6B7C5E]">California</em></h2><p className={`text-[#7A6556] text-base font-light max-w-xl mx-auto transition-all duration-700 delay-200 ${v?"opacity-100":"opacity-0"}`}>If you hold a California address, Dr. Gill can see you — no matter where in the state you live.</p></div>
    <div className={`flex flex-wrap gap-2 justify-center transition-all duration-700 delay-300 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`}>
      {cities.map((c,i)=>(<span key={c} className="text-[10px] tracking-widest uppercase border border-[#6B7C5E]/25 text-[#6B7C5E] px-3 py-1.5 hover:bg-[#6B7C5E]/10 transition-colors duration-200" style={{transitionDelay:`${i*20}ms`}}>{c}</span>))}
      <span className="text-[10px] tracking-widest uppercase border border-[#B8925A]/30 text-[#B8925A] px-3 py-1.5 bg-[#B8925A]/5">+ All Other CA Cities</span>
    </div>
  </div></section>);
}
function WhyCover(){
  const[ref,v]=useReveal();
  const items=[{t:"Same Expert Care",d:"Dr. Gill's telehealth appointments are identical in quality to in-person visits — same evaluation depth, same treatment planning, same follow-up."},{t:"Insurance Covered",d:"Most major insurance plans now cover telehealth psychiatric visits in California at the same rate as in-person care."},{t:"HIPAA-Compliant",d:"All sessions use a bank-level encrypted video platform. Your privacy and confidentiality are fully protected."},{t:"No Travel Required",d:"See Dr. Gill from anywhere in California — eliminating travel time, gas costs, and the need to take time off work."}];
  return(<section className="py-24 px-5 md:px-10 bg-[#FDFAF6]"><div className="mx-auto max-w-7xl">
    <div ref={ref} className="text-center mb-14"><div className={`flex items-center justify-center gap-3 mb-5 transition-all duration-700 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`}><span className="w-12 h-px bg-[#B8925A]/50"/><Dm size={7}/><span className="w-12 h-px bg-[#B8925A]/50"/></div><h2 className={`text-5xl md:text-6xl text-[#2C1A0E] transition-all duration-700 delay-100 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`} style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:300}}>Why Telehealth <em className="italic text-[#B8925A]">Works</em></h2></div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
      {items.map((it,i)=>(<div key={it.t} className={`group bg-[#F5EEE4] border border-[#E8D5BE] p-8 transition-all duration-700 hover:-translate-y-2 hover:shadow-[0_14px_48px_rgba(184,146,90,0.13)] hover:border-[#B8925A]/50 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-10"}`} style={{transitionDelay:`${i*110}ms`,transitionDuration:"700ms"}}><div className="absolute top-0 left-0 right-0 h-[2px] bg-[#B8925A] scale-x-0 group-hover:scale-x-100 transition-transform duration-500 origin-left relative"/><p className="text-[32px] text-[#B8925A]/20 leading-none mb-4" style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:300}}>{String(i+1).padStart(2,"0")}</p><h3 className="text-xl text-[#2C1A0E] mb-3" style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:500}}>{it.t}</h3><p className="text-[#7A6556] text-sm leading-relaxed font-light">{it.d}</p></div>))}
    </div>
  </div></section>);
}
function FAQSec(){
  const[ref,v]=useReveal();const[open,sOpen]=useState(null);
  const faqs=[{q:"Do I need to live near Fremont to use telehealth?",a:"No. Dr. Gill's telehealth services are available to any patient with a California address — from San Diego to Sacramento, the Bay Area to the Central Valley."},{q:"What do I need for a telehealth appointment?",a:"A smartphone, tablet, or computer with a camera and microphone, and a stable internet connection. Our HIPAA-compliant video platform works directly in your browser — no app needed."},{q:"Are telehealth appointments covered by insurance?",a:"Most major insurance plans cover telehealth psychiatric visits in California. Our staff verifies your telehealth benefits when you call, at no charge to you."},{q:"Can Dr. Gill prescribe medications via telehealth?",a:"Yes. Dr. Gill can prescribe and manage psychiatric medications via telehealth, including refills and adjustments, for patients in California."},{q:"Is a telehealth appointment as thorough as in-person?",a:"Yes. Dr. Gill conducts the same comprehensive evaluations and maintains the same standard of care via telehealth. The only difference is the medium, not the quality."}];
  return(<section className="py-24 px-5 md:px-10 bg-[#F5EEE4]"><div className="mx-auto max-w-4xl"><div ref={ref} className={`text-center mb-12 transition-all duration-700 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`}><h2 className="text-5xl md:text-6xl text-[#2C1A0E]" style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:300}}>Telehealth <em className="italic text-[#B8925A]">Questions</em></h2></div>
  <div className="space-y-3">{faqs.map((f,i)=>(<div key={f.q} className={`border transition-all duration-500 ${open===i?"border-[#B8925A]/50 bg-[#FDFAF6]":"border-[#E8D5BE] bg-[#FDFAF6]/70 hover:border-[#B8925A]/30"} ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-6"}`} style={{transitionDelay:`${i*55}ms`,transitionDuration:"600ms"}}><button className="w-full flex items-center justify-between px-6 py-5 text-left gap-4" onClick={()=>sOpen(open===i?null:i)}><span className="text-[15px] font-medium text-[#2C1A0E]">{f.q}</span><span className={`flex-shrink-0 w-7 h-7 border flex items-center justify-center transition-all duration-300 ${open===i?"border-[#B8925A] bg-[#B8925A] text-[#FDFAF6] rotate-45":"border-[#E8D5BE] text-[#B8925A]"}`}><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg></span></button><div className={`overflow-hidden transition-all duration-400 ${open===i?"max-h-48 pb-6":"max-h-0"}`}><p className="px-6 text-[#7A6556] text-sm leading-relaxed font-light">{f.a}</p></div></div>))}</div></div></section>);
}
function CTA(){
  const[ref,v]=useReveal();
  return(
    <section className="py-28 px-5 md:px-10 relative overflow-hidden text-center" style={{background:"linear-gradient(160deg,#FDFAF6 0%,#F5EEE4 50%,#EDE5D6 100%)"}}>
      <div className="absolute top-1/2 left-1/4 -translate-y-1/2 w-80 h-80 rounded-full pointer-events-none" style={{background:"radial-gradient(circle,rgba(184,146,90,0.14) 0%,transparent 70%)"}} />
      <div ref={ref} className="relative mx-auto max-w-2xl">
        {/* BOTH DOCTORS — 50/50 partners, every page */}
        <div className={`transition-all duration-700 ${v?"opacity-100 scale-100":"opacity-0 scale-90"}`}>
          <DoctorAvatars className="mb-10"/>
        </div>
        <div className={`flex items-center justify-center gap-3 mb-6 transition-all duration-700 delay-100 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`}>
          <span className="w-16 h-px bg-[#B8925A]/40"/><Dm/><span className="w-16 h-px bg-[#B8925A]/40"/>
        </div>
        <h2 className={`text-5xl md:text-[64px] text-[#2C1A0E] mb-5 transition-all duration-700 delay-150 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-8"}`}
          style={{fontFamily:"'Cormorant Garamond',serif",fontWeight:300,lineHeight:1.05}}>
          California-Wide<br/><em className="italic text-[#B8925A]">Expert Care.</em>
        </h2>
        <p className={`text-[#7A6556] text-lg font-light max-w-lg mx-auto mb-10 leading-relaxed transition-all duration-700 delay-200 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-6"}`}>Book your telehealth appointment with Dr. Gill or Dr. Gondara. Your first consultation is completely free.</p>
        <div className={`flex flex-col sm:flex-row items-center justify-center gap-4 transition-all duration-700 delay-300 ${v?"opacity-100 translate-y-0":"opacity-0 translate-y-6"}`}>
          <a href="tel:5105984921" className="group flex items-center gap-3 bg-[#2C1A0E] text-[#F0E8DA] px-10 py-[18px] text-[11px] font-bold tracking-[0.2em] uppercase hover:bg-[#B8925A] transition-colors duration-400"><Ph/> Call (510) 598-4921 <span className="group-hover:translate-x-1.5 transition-transform duration-300">→</span></a>
          <a href="/contact" className="flex items-center gap-2 border border-[#B8925A]/50 text-[#B8925A] px-10 py-[18px] text-[11px] font-bold tracking-[0.2em] uppercase hover:border-[#B8925A] hover:bg-[#B8925A]/5 transition-all duration-300">Send a Message</a>
        </div>
        <p className={`mt-7 text-[10px] tracking-[0.2em] uppercase text-[#7A6556]/45 transition-all duration-700 delay-400 ${v?"opacity-100":"opacity-0"}`}>Mon – Fri · 9:30 AM – 5:30 PM · 680 Mowry Ave, Fremont, CA · Telehealth Statewide CA</p>
      </div>
    </section>
  );
}
function Ph(){return <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07A19.5 19.5 0 013.07 9.81 19.79 19.79 0 012 2.93h3a2 2 0 012 1.72c.127.96.361 1.903.7 2.81a2 2 0 01-.45 2.11L6.09 8.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0122 16.92z"/></svg>;}
function Dm({size=8}){return <svg width={size} height={size} viewBox="0 0 10 10" fill="#B8925A"><polygon points="5,0 10,5 5,10 0,5"/></svg>;}
const CSS=`*{cursor:none !important;}@keyframes fadeUp{from{opacity:0;transform:translateY(32px)}to{opacity:1;transform:translateY(0)}}@keyframes floatOrb{0%,100%{transform:translate(0,0) scale(1)}33%{transform:translate(22px,-30px) scale(1.06)}66%{transform:translate(-14px,18px) scale(0.94)}}@keyframes marquee{from{transform:translateX(0)}to{transform:translateX(-50%)}}@keyframes scrollLine{0%{transform:translateY(-100%)}100%{transform:translateY(200%)}}`;